server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:file:~/test
    password: ''
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  jpa:
    defer-datasource-initialization: 'true'
    properties:
      hibernate:
        format_sql: 'true'
        ddl-auto: update
    show-sql: 'true'
