spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'false'
    hibernate:
      ddl-auto: none
    show-sql: 'false'
  datasource:
    url: mysql://b5bf5e161a7689:14a9e8e3@us-cdbr-east-05.cleardb.net/heroku_e16ea79c4c6005f?reconnect=true
    